# Generated by Django 4.2.1 on 2023-08-14 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_room_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='descriptioin',
            new_name='description',
        ),
    ]
