# Generated by Django 4.2.1 on 2023-05-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testAPP', '0002_test_created_att_alter_test_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='created_att',
        ),
        migrations.AlterField(
            model_name='test',
            name='created_at',
            field=models.CharField(default='defualt', max_length=50),
        ),
    ]
