# Generated by Django 4.2.1 on 2023-05-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testAPP', '0004_test_created_att_alter_test_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='babybear',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
