# Generated by Django 4.2.1 on 2023-06-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0002_experience_category'),
        ('rooms', '0005_room_category'),
        ('wishlists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='room',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='experiences',
            field=models.ManyToManyField(blank=True, null=True, to='experiences.experience'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='rooms',
            field=models.ManyToManyField(blank=True, null=True, to='rooms.room'),
        ),
    ]
