# Generated by Django 4.2.1 on 2023-06-13 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0002_remove_wishlist_experience_remove_wishlist_room_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='experiences',
            new_name='experience',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='rooms',
            new_name='room',
        ),
    ]
