# Generated by Django 4.2.1 on 2023-06-13 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0003_rename_experiences_wishlist_experience_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='experience',
            new_name='experiences',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='room',
            new_name='rooms',
        ),
    ]
