# Generated by Django 4.2.1 on 2023-05-16 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('direct_messages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='participants',
            new_name='participant',
        ),
    ]
